export const userActions = {
  LOGIN_AS_ANONYMOUS: 'LOGIN_AS_ANONYMOUS',
  SEND_OTP: 'SEND_OTP',
  VERIFY_OTP: 'VERIFY_OTP',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_AUTH_STATUS: 'UPDATE_AUTH_STATUS',
  SET_AUTH_CONFIRM: 'SET_AUTH_CONFIRM',
  SET_OTP_STATUS: 'SET_OTP_STATUS',
  LOGOUT: 'LOGOUT',
};

export const appActions = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
};
